### ISSUE TITLE
java.lang.NoClassDefFoundError when using command line

### ISSUE THREAD

**Issue by jmbruel** [asciidoctor/asciidoclet#38]
I am trying to use asciidoclet in command line:

javadoc ... -doclet org.asciidoctor.Asciidoclet -docletpath doclet/asciidoclet-1.5.0.jar ...

And I get:
javadoc: error - In doclet class org.asciidoctor.Asciidoclet,  method optionLength has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList

Any idea? Thanks in advance

**Comment by johncarl81** [comment]
This should be available in the upcoming 1.5.3 release.
