### ISSUE TITLE
Publish JavaDoc for AsciiDoclet

### ISSUE THREAD

**Issue by msgilligan** [asciidoctor/asciidoclet#46]
It would be nice to see the JavaDoc for this project published. As I mentioned in a comment on another issue, I'm looking for examples of Asciidoclet being used in real-world projects. I decided to see if there was any dog-food eating going on -- and there was! -- but it would be nice to see the rendered HTML published somewhere.

**Comment by johncarl81** [comment]
It's published on maven: https://oss.sonatype.org/service/local/repositories/releases/archive/org/asciidoctor/asciidoclet/1.5.2/asciidoclet-1.5.2-javadoc.jar/!/index.html

**Comment by msgilligan** [comment]
Cool! Should I add a link to the README and send a PR?

**Comment by msgilligan** [comment]
I just noticed that the published link you provided was to a JAR file. I was also surprised to learn that Safari and Chrome will open and display it. Firefox doesn't, though. I don't know about IE.

I'll add the link to the README anyway, and maybe we can find a place to publish it as HTML.

**Comment by msgilligan** [comment]
PR #49 Adds a link to the published Maven JavaDoc JAR. 

We could close this issue or leave it open to remind us to publish the JavaDoc somewhere as exploded HTML.

**Comment by johncarl81** [comment]
Im comfortable closing this.  I like the idea of publishing to a non-maven-central location, but I think it does the job.

**Comment by johncarl81** [comment]
FYI: #55
