### ISSUE TITLE
List of AsciiDoclet-powered projects

### ISSUE THREAD

**Issue by msgilligan** [asciidoctor/asciidoclet#48]
It would be great to have a curated list of Asciidoclet-powered projects somewhere. We can use this issue to collect a list and I'll put together a pull request to put them somewhere.

I did find [this Google+ post](https://plus.google.com/114112334290393746697/posts/NHPfhyNXnM1) by @mojavelinux

**Comment by msgilligan** [comment]
This comment will contain the working list. Feel free to edit it.

* [asciidoctor/asciidoclet](https://github.com/asciidoctor/asciidoclet) - Dog food is yummy!
* [Java EE samples](http://javaee.support): [source example](https://github.com/javaee-samples/javaee7-samples/blob/master/jaxrs/async-client/src/test/java/org/javaee7/jaxrs/asyncclient/MyResourceTest.java) [rendered example](http://javaee.support/sample/jaxrs-async-client/index.html)

**Comment by johncarl81** [comment]
I use it on my projects:
[Transfuse](androidtransfuse.org) - [docs](https://oss.sonatype.org/service/local/repositories/releases/archive/org/androidtransfuse/transfuse-api/0.3.0-beta-7/transfuse-api-0.3.0-beta-7-javadoc.jar/!/index.html)
[Parceler](paceler.org) - [docs](https://oss.sonatype.org/service/local/repositories/releases/archive/org/parceler/parceler-api/1.0.3/parceler-api-1.0.3-javadoc.jar/!/index.html)

**Comment by johncarl81** [comment]
I use it on my projects:
[Transfuse](https://oss.sonatype.org/service/local/repositories/releases/archive/org/androidtransfuse/transfuse-api/0.3.0-beta-7/transfuse-api-0.3.0-beta-7-javadoc.jar/!/index.html)
[Parceler]()

**Comment by mojavelinux** [comment]
It's probably best if we add an Asciidoclet section to the following planned page.

https://github.com/asciidoctor/asciidoctor.org/issues/270

**Comment by msgilligan** [comment]
Well, I'd like to create something just for AsciiDoclet -- perhaps as simple as a `powered-by.adoc` file in this repository. We can always merge into the "planned" page when that page is ready.

**Comment by mojavelinux** [comment]
Of course, that's perfectly fine too. It will just be nice to see it highlighted on the main "who's using" page as well.

**Comment by msgilligan** [comment]
PR #49 puts all the projects listed above in `doc/asciidoclet-powered.adoc`. Once merged, this issue can be closed. https://github.com/asciidoctor/asciidoctor.org/issues/270 can include this list and, once completed, we can remove this list from this site and link to the section in the project-wide list.

**Comment by msgilligan** [comment]
Implemented by PR #49.
