### ISSUE TITLE
output comments to separate files

### ISSUE THREAD

**Issue by lgazo** [asciidoctor/asciidoclet#56]
Greetings,

would it be possible to create separate files for each comment in order to link it to another Asciidoc-based documentation?

Example use-case:
- I write description of a class, its fields and methods with asciidoc
- Next to it I write general documentation of how to use it
- I want to keep documentation on one place and therefore I want to relate from "general documentation" to class description or field description with "include" directive.
- So asciidoclet could generate files like: "com.acme.SuperClass" containing asciidoc comment and "com.acme.SuperClass#fancyField" containing asciidoc comment on SuperClass' fancyField field in e.g. /target/asciidoc

Would it be possible to hook such behaviour into asciidoclet?

Thanks.

**Comment by johncarl81** [comment]
Something like this:? 
http://discuss.asciidoctor.org/Export-Javadoc-strings-td4172.html
https://github.com/johncarl81/exportdoclet

I'd really like to hear your experience with this doclet as it's brand new.

**Comment by johncarl81** [comment]
Related: https://github.com/asciidoctor/asciidoclet/issues/42

**Comment by lgazo** [comment]
yes, that looks exactly as what I am looking for :)
