### ISSUE TITLE
Set attribute `env-asciidoclet` by default

### ISSUE THREAD

**Issue by lefou** [asciidoctor/asciidoclet#57]
This would ease custom processing for Javadoc, e.g. with `ifdef::`.

**Comment by johncarl81** [comment]
Do other libraries in the asciidoctor ecosystem set a similar attribute?

**Comment by lefou** [comment]
Yes. E.g. on GitHub, there is `env-github`. The [asciidoctor plugin for gitbucket](https://github.com/asciidoctor/gitbucket-asciidoctor-plugin) sets `env-gitbucket`.

See also http://asciidoctor.org/news/2014/02/04/github-asciidoctor-0.1.4-upgrade-5-things-to-know/#long-live-asciidoc-on-github

**Comment by lefou** [comment]
Additionally, `env=asciidoclet` would be a good idea too.

**Comment by johncarl81** [comment]
WDYT?: #58

**Comment by johncarl81** [comment]
setting `env` has the possibility to collide between libraries btw.  Asciidoclet uses Asciidoctorj, which I imagine could set a similar `env=asciidoctorj`.

**Comment by johncarl81** [comment]
@lefou, Im curious, what is your use-case for this?

**Comment by lefou** [comment]
asciidoctorj does not set `env` attribute, and current usage of the `env` attribute in other places (and my conversations with @mojavelinux ) suggest it is meant the way we want it to use it here. Also gitbucket-asciidoctor-plugin is also based on asciidoctorj.

My current use case was reusing the project `README.adoc`, which is the entry point documentation on GitHub, also as the overview page in the JavaDoc. Of course some links are different and need to be handled conditionally for each environment. E.g. `src/main/java` prefix or not, `.java` or `.html` file ending, etc.

```adoc
ifdef::env-github,env-gitbucket[:outfilesuffix: .adoc]
ifndef::env-asciidoclet[:srcdir: src/main/java/]
ifdef::env-asciidoclet[:srcdir:]
ifndef::env-asciidoclet[:javasuffix: .java]
ifdef::env-asciidoclet[:javasuffix: .html]

link:{srcdir}org/example/Main{javasuffix}[`Main`]
```

**Comment by johncarl81** [comment]
Makes sense.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
Correct. `env` is the execution environment, not which implementation of the processor is being used. In other words, it describes where the document is being converted. We set this in plugins such as a static site generator, so it makes a lot of sense to set it here too.
