### ISSUE TITLE
Use of Javadoc annotations such as @link or @see

### ISSUE THREAD

**Issue by mattadamson** [asciidoctor/asciidoclet#65]
Hi

How do others use previous JavaDoc annotation such as @link and @see in the Ascii doc formatted documentation? e.g. if we want to reference another class from a class definition we'd use

{@link classwithpackageidentifier}

Many thanks

Matt

**Comment by johncarl81** [comment]
Asciidoclet will just enhance the tag's text, the annotation tags shoudl work as they did before.  For me, `@see` referencing a class within the same project will create a link to that class.
