### ISSUE TITLE
readme.adoc currently broken

### ISSUE THREAD

**Issue by gernotstarke** [asciidoctor/asciidoclet#68]
<img width="929" alt="screenshot 2018-01-08 17 08 48" src="https://user-images.githubusercontent.com/1233990/34679598-c3463236-f496-11e7-8a08-1933f8e23866.png">

Suggestion: remove some of the ifdef's - as the readme.adoc will probably only be rendered on Github...

**Comment by msgilligan** [comment]
According to PR #66 the README is also used on asciidoctor.org. That PR may also be what broke the README.

@mojavelinux ?

**Comment by mojavelinux** [comment]
There was a typo in the header. I can't believe we didn't see this until now. Thanks for drawing our attention to it, @gernotstarke!
