### ISSUE TITLE
Publish a 1.5.5-SNAPSHOT build

### ISSUE THREAD

**Issue by msgilligan** [asciidoctor/asciidoclet#79]
So now that we have preliminary support for running under Java 9+, it would be nice to make a SNAPSHOT release.

Is there documentation on how this is done? Who as been doing this? What should we do?

**Comment by johncarl81** [comment]
You just need to run the following Maven command to deploy a snapshot:
```
mvn clean deploy
```
Give it a try... You may need a pgp key or something for access to maven central.  We can work through this if it doesn't work OOTB.

I've taken the liberty to deploy it: https://oss.sonatype.org/content/repositories/snapshots/org/asciidoctor/asciidoclet/1.5.5-SNAPSHOT/

**Comment by msgilligan** [comment]
Thanks @johncarl81 -- I've [updated](https://github.com/ConsensusJ/consensusj/commit/92c75fca19071bf1719f71fe2d59203010ac4156) ConsensusJ to use it and published [HTML5 JavaDocs](https://consensusj.github.io/consensusj/apidoc/) with search as generated by Asciidoclet + Java 9.

**Comment by johncarl81** [comment]
Cool, the new search feature is nice!

**Comment by msgilligan** [comment]
Closing as a snapshot release has been made and PR #82 starts a release process document with all the information provided above by @johncarl81 .

Next step is probably to go ahead and make an official release of version 1.5.5...
