### ISSUE TITLE
Asciidoclet fails with "invalid flag error" on Java 10

### ISSUE THREAD

**Issue by msgilligan** [asciidoctor/asciidoclet#81]
When I try to run the current Asciidoclet 1.5.5-SNAPSHOT with Java 10 via the Gradle javadoc task I get the following error:

```
javadoc: error - invalid flag: -d
```

This is because the old "Standard Doclet" was removed in Java 10 (http://www.oracle.com/technetwork/java/javase/10-relnote-issues-4108729.html#JDK-8177511) and Asciidoclet runs as a preprocessor that in-turn calls the Standard Doclet.

I'm not sure if this is worth trying to fix separately from Issue #71. In other words there are two approaches to resolving this:

1. Create an Asciidoclet that implements the new JavaDoc API and have this new Asciidoclet call the new standard doclet for generating HTML. i.e. Issue #71 
2. Update the current Asciidoclet to use the new Standard Doclet w/o Asciidoclet itself implementing the new JavaDoc API. (I don't even know if this is possible)

So, it seems to me like #71 is probably the best solution. But there may be other solutions and we need to track this specific issue that we are seeing under Java 10+.

**Comment by johncarl81** [comment]
Agreed, we should just move to the new API as you state in option 1 - option 2 is working in the wrong direction.

**Comment by gsmet** [comment]
I think I might have a similar issue with JDK 11 and the `-Xdoclint` option.

It would be nice if we could find a solution as the Hibernate ORM 6 javadoc is now heavily relying on Asciidoclet and we still have a lot of legacy javadoc that needs some fixing thus the use of the `-Xdoclint` option (we will fix it eventually but we are not in a good position to right now).

**Comment by chrisvest** [comment]
I'm also running into this on Java 11. Specifically I'm seeing that the `-author` flag is invalid.

**Comment by msgilligan** [comment]
It seems like we've decided to move to the new JavaDoc API (Issue #71) and we have a PR for it (PR #96) so I'm going to close this issue as essentially a duplicate.
