### ISSUE TITLE
1.5.6 not available in maven central

### ISSUE THREAD

**Issue by romain-grecourt** [asciidoctor/asciidoclet#93]
The latest version available in maven central is 1.5.4, see http://repo1.maven.org/maven2/org/asciidoctor/asciidoclet/

I can see 1.5.6 available on bintray.

**Comment by johncarl81** [comment]
Just synced bintray with maven central... 1.5.6 should be available later on today.

**Comment by romain-grecourt** [comment]
The artifacts are now available in Maven Central. Thanks !
